#!/usr/bin/env sh

#
# © 2021 Thoughtworks, Inc.
#

echo GCP_USE_BILLING_DATA=$GCP_USE_BILLING_DATA >> .env
echo GCP_USE_CARBON_FREE_ENERGY_PERCENTAGE=$GCP_USE_CARBON_FREE_ENERGY_PERCENTAGE >> .env
echo GCP_VCPUS_PER_GKE_CLUSTER=$GCP_VCPUS_PER_GKE_CLUSTER >> .env
echo GCP_VCPUS_PER_CLOUD_COMPOSER_ENVIRONMENT=$GCP_VCPUS_PER_CLOUD_COMPOSER_ENVIRONMENT >> .env
echo GCP_PROJECTS=$GCP_PROJECTS >> .env
echo GCP_BIG_QUERY_TABLE=$GCP_BIG_QUERY_TABLE >> .env
echo GCP_BILLING_PROJECT_ID=$GCP_BILLING_PROJECT_ID >> .env
echo GCP_BILLING_PROJECT_NAME=$GCP_BILLING_PROJECT_NAME >> .env
echo LOGGING_MODE="GCP" >> .env
echo GENERATE_SOURCEMAP="false" >> .env
echo GROUP_QUERY_RESULTS_BY=$GROUP_QUERY_RESULTS_BY >> .env
echo GCS_CACHE_BUCKET_NAME=$GCS_CACHE_BUCKET_NAME >> .env
echo CACHE_MODE=$CACHE_MODE >> .env
echo MONGODB_URI=$MONGODB_URI >> .env
echo MONGODB_CREDENTIALS=$MONGODB_CREDENTIALS >> .env
